### ISSUE TITLE
Compatibility with MathJax

### ISSUE THREAD

**Issue by TheWiseMan** [widcardw/asciimath-parser#17]
Hey there, can your packages be used as a mathjax extension ?

**Comment by widcardw** [comment]
Yes, of course. This package simply parse asciimath into LaTeX formulas, so the pipeline should be

```
asciimath formula -- am-parser --> tex -- KaTeX/MathJax/LaTeX --> your document
```

**Comment by widcardw** [comment]
I'm not sure how to compile it into wasm or other libs... I have created a cli that can parse a file with asciimath into tex file, and it is compiled by node.

**Comment by TheWiseMan** [comment]
I see, I might rewrite some of your code.
One last question, if you don't mind, do you recommend the use of the nearley parser or the core one ?

**Comment by TheWiseMan** [comment]
Thanks a lot for your answers, I managed to do what I wanted, I'll send it to you after refactoring (as an example of using your asciimath with mathjax for browsers)
